[project]
authors = ["kseuro <kai.w.stewart@gmail.com>"]
channels = ["pytorch", "conda-forge", "https://conda.modular.com/max"]
description = "A learning exercise in applying MAX to neural networks written in PyTorch."
name = "neural-networks-zero-to-one"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
python = "3.11.*"
ipykernel = ">=6.29.5,<7"
jupyterlab = ">=4.2.5,<5"
numpy = ">=1.26.4,<2"
matplotlib = ">=3.9.2,<4"
python-graphviz = ">=0.20.3,<0.21"
pydot = ">=3.0.2,<4"
pytorch = ">=2.5.1,<3"
pandas = ">=2.2.3,<3"
seaborn = ">=0.13.2,<0.14"
multicore-tsne = ">=0.1_d4ff4aab,<0.2"
graphviz = ">=12.0.0,<13"
tiktoken = ">=0.8.0,<0.9"
tqdm = ">=4.67.1,<5"
